### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by aadilayub** [oae/gnome-shell-pano#284]
The `validate-color` package seems to be missing a manifest?

```
gnome-shell-pano on  master [!?] via  v20.12.2 took 3s 
❯ yarn install
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0014: │ validate-color@https://gitpkg.now.sh/dreamyguy/validate-color/src/validate-color: Only some patterns can be imported from legacy lockfiles (not "https://gitpkg.now.sh/dreamyguy/validate-color/src/validate-color#9e890cb48fed5e22027a67d98750232c4ce780f6")
➤ YN0001: │ Error: validate-color@https://gitpkg.now.sh/dreamyguy/validate-color/src/validate-color: Manifest not found
    at AE.find (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:140:120021)
    at async /var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:559:12938
    at async Object.xZe (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:140:53847)
    at async G2.resolve (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:559:12899)
    at async Pd.resolve (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:141:1451)
    at async Pd.resolve (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:141:1451)
    at async /var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:210:7249
    at async Ky (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:140:53910)
    at async ne (/var/home/aadil/.dev/gnome-shell-pano/.yarn/releases/yarn-4.2.2.cjs:210:7231)
    at async Promise.allSettled (index 55)
➤ YN0000: └ Completed in 0s 576ms
➤ YN0000: · Failed with errors in 0s 602ms
```

I'm running the latest version of yarn, node v20, and Fedora 40 as the base system.

**Comment by segher86** [comment]
When using `yarn set version 1.22.22` it worked for me.

**Comment by aadilayub** [comment]
> When using `yarn set version 1.22.22` it worked for me.

this worked! thanks. Should probably add that to the README.

**Comment by EPOCHvoyager** [comment]
Getting a "payment required" error now. Above workaround doesn't seem to work anymore. If you visit the website in a web browser, there's now a "This deployment is temporarily paused" message.

```
$ yarn install
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
(node:23244) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
error Error: https://gitpkg.now.sh/dreamyguy/validate-color/src/validate-color: Request failed "402 Payment Required"
```

**Comment by martinmilani** [comment]
> Getting a "payment required" error now. Above workaround doesn't seem to work anymore. If you visit the website in a web browser, there's now a "This deployment is temporarily paused" message.
> 
> ```
> $ yarn install
> yarn install v1.22.22
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> (node:23244) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> [3/5] Fetching packages...
> info There appears to be trouble with your network connection. Retrying...
> error Error: https://gitpkg.now.sh/dreamyguy/validate-color/src/validate-color: Request failed "402 Payment Required"
> ```

same problem here
Try replace
`"validate-color": "https://gitpkg.now.sh/dreamyguy/validate-color/src/validate-color"` (no longer working)
with: 
` "validate-color": "^2.2.4"`
In the package.json

**Comment by EPOCHvoyager** [comment]
```
Extension pano@elhan.io: SyntaxError: The requested module 'file:///home/crono/.local/share/gnome-shell/extensions/pano@elhan.io/thirdparty/validate_color.js' doesn't provide an export named: 'validateHTMLColorHex' @ file:///home/crono/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js:59:10
```

Compiles, but breaks the extension in practice.
