### ISSUE TITLE
Failure during locale build step

### ISSUE THREAD

**Issue by rsilvr** [oae/gnome-shell-pano#331]
## Description

This is not a problem with the distributed version of the extension itself, but I got an error while trying to run `yarn build` in the master branch (currently at [this commit](https://github.com/oae/gnome-shell-pano/commit/d0d71f8015ada661f35a1390502c8e09fa2a10b6)).

### Problem Explanation

(Output summarized)
```
src/prefs/prefs.ts → dist/prefs.js...
created dist/prefs.js in 1.9s

tests/db.test.ts → build/tests/db.test.js...
created build/tests/db.test.js in 1.9s
$ yarn run ts-node scripts/generateLocale.ts
$ /home/my-user/dev/side/gnome-shell-pano/node_modules/.bin/ts-node scripts/generateLocale.ts

/home/my-user/dev/side/gnome-shell-pano/node_modules/gettext-extractor/dist/utils/output.js:11
        return chalk ? chalk.green(value) : value;
                             ^
TypeError: chalk.green is not a function
    at Function.green (/home/my-user/dev/side/gnome-shell-pano/node_modules/gettext-extractor/dist/utils/output.js:11:30)
    at StatsOutput.print (/home/my-user/dev/side/gnome-shell-pano/node_modules/gettext-extractor/dist/utils/output.js:54:45)
    at GettextExtractor.printStats (/home/my-user/dev/side/gnome-shell-pano/node_modules/gettext-extractor/dist/extractor.js:76:51)
    at extractStrings (/home/my-user/dev/side/gnome-shell-pano/scripts/generateLocale.ts:32:15)
    at main (/home/my-user/dev/side/gnome-shell-pano/scripts/generateLocale.ts:67:3)
    at Object.<anonymous> (/home/my-user/dev/side/gnome-shell-pano/scripts/generateLocale.ts:98:1)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Module.m._compile (/home/my-user/dev/side/gnome-shell-pano/node_modules/ts-node/src/index.ts:1618:23)
    at node:internal/modules/cjs/loader:1708:10
    at Object.require.extensions.<computed> [as .ts] (/home/my-user/dev/side/gnome-shell-pano/node_modules/ts-node/src/index.ts:1621:12)
```

As a workaround, I skipped the script `gen:locale` from the build so it could get to the compilation of the extension.

**Comment by Totto16** [comment]
I can reproduce this locally, but it worked in the [last action that run succesfully](https://github.com/oae/gnome-shell-pano/actions/runs/11273805189) 🤦🏼‍♂️ 

I'll investigate 👍🏼
